name: container deployment CD Pipeline
run-name: remote deployment
on: [push]
  # workflow_dispatch:

env:
  IMAGE_NAME: thiyaga

jobs:
  deploy :
    runs-on: self-hosted

    steps:
      - name: Deploy to remote VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TARGET_SERVER }}
          username: ${{ secrets.TARGET_SSH_USER }}
          key: ${{ secrets.TARGET_SSH_KEY }}
          script: |
            echo "Pulling latest Docker image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/thiyaga:latest 

            echo "Stopping old container (if exists)..."
            docker stop thiyaga || true
            docker rm thiyaga || true

            echo "Starting new container..."
            docker run -d \
              --name $IMAGE_NAME \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest


            echo "Deployment complete!"


